apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: nginx
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-pk
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:1.23
        
