apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-rs
    type: front-end
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: myapp-container
        image: nginx:1.23
        ports:
        - containerPort: 80
